// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config, validateConfig } from '@/config/env';

// Verificar se as variáveis estão configuradas
if (!validateConfig()) {
  console.error('Supabase configuration validation failed');
}

console.log('Initializing Supabase client with URL:', config.supabase.url);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(config.supabase.url, config.supabase.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Testar conexão na inicialização
supabase
  .from('user_accounts')
  .select('count')
  .limit(1)
  .then(({ data, error }) => {
    if (error) {
      console.error('Supabase connection test failed:', error);
    } else {
      console.log('Supabase connection test successful');
    }
  })
  .catch((error) => {
    console.error('Supabase connection test error:', error);
  });