// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eywqybkwinmbpxkmdfkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5d3F5Ymt3aW5tYnB4a21kZmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzA3MTQsImV4cCI6MjA2Njc0NjcxNH0.IzloGBQNXbb1bjvaarF8OcT9QKmpt-m9GXFoIS4rez0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});